language: julia
os:
  - osx
  - linux
julia:
  - 0.7
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("BIGUQ"); Pkg.test("BIGUQ"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("BIGUQ")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'